name: Trigger auto deployment for km-service-5c0cc9

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/km-service-5c0cc9-AutoDeployTrigger-b23ac7d8-af23-4149-978d-b0a43603cc7d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KMSERVICE5C0CC9_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KMSERVICE5C0CC9_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KMSERVICE5C0CC9_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: qigkernelmemoryacr.azurecr.io
          registryUsername: ${{ secrets.KMSERVICE5C0CC9_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KMSERVICE5C0CC9_REGISTRY_PASSWORD }}
          containerAppName: km-service-5c0cc9
          resourceGroup: rg-qig-km-4
          imageToBuild: qigkernelmemoryacr.azurecr.io/km-service-5c0cc9:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


